### ISSUE TITLE
Insufficient CPU to make transactions

### ISSUE THREAD

**Issue by ptrwtts** [zachalam/namevault.co#2]
Just a suggestion....

The reason this service is nice, is because it allows someone to get started quickly. But the amount staked towards CPU and Network (0.01 each) is not enough to actually make transactions. I tried posting on https://eos-forum.org/ but only had around 25% of the required CPU. I would suggest charging more and staking at least 0.05 CPU, so that people can actually try out some dApps (unless you know of some dApps that use less).

**Comment by zachalam** [comment]
Hi ptrwtts, thanks for your suggestion. I also share this same view. I will be adding a feature in the coming week that will add the option to stake 0.1 CPU/BW for a small fee (just the price of the extra EOS). That way the purchaser can decide whether the extra cost is justified for that particular account.

**Comment by zachalam** [comment]
Awesome idea, definitely appreciate your feedback and will let you know when the new feature is added. I am going to close this for the time being.

**Comment by zachalam** [comment]
![image](https://user-images.githubusercontent.com/832764/43655956-8f6b287e-9705-11e8-8b76-2ff3299855f6.png)
Quick Update, this feature has been added (as of today). A checkbox is now available above the purchase button to stake more resources. Hopefully this helps @ptrwtts . 
![image](https://user-images.githubusercontent.com/832764/43655969-9d4be2bc-9705-11e8-98b7-bdcc2d630bd7.png)
