### ISSUE TITLE
private owner key / private active key?

### ISSUE THREAD

**Issue by tristanbuist** [zachalam/namevault.co#3]
Hello namevault!

I bought an account from you a couple of days ago (tristanbuist)...

I was given a 'private key', but now I am trying to add my account to EOS voter 0.4.1 and they require both a 'private owner key' and 'private active key', but I was only given the single 'private key'. 

Did I not notice there were two keys or was I only given one key?

Thanks
Tristan

**Comment by zachalam** [comment]
Hi Tristan, 
First off, thanks for your purchase! Here's how namevault.co works when assigning keys:
a) If only a `owner public key` is provided: The `owner public key` is used as both the owner permission and the active permission (same key).
b) If both a `owner public key` and `active public key` are provided: The `owner public key` is used as the owner permission and the `active public key` is used as the active permission.

I looked up your account **tristanbuist** and it appears it was created by another service called **leckoaccount** (not namevault.co which is **blockexpress**). I, unfortunately, do not know how that service creates accounts.

Please let me know if this helps.

**Comment by zachalam** [comment]
Hi Tristan. Haven't heard back from you. Going to close this issue, feel free to open another if you have any other further problems!

**Comment by tristanbuist** [comment]
All sorted, thanks mate, please close!

Tristan
