### ISSUE TITLE
Paid but did not receive a name

### ISSUE THREAD

**Issue by feiyan-cs** [zachalam/namevault.co#4]
Coinbase pay finished payment but your website did not have any response.

The key I provided is EOS8csEeHQGeEn7ixuw3HbF3TQCMSGfhEKXzPGT2hQCVsCWH73TRk

https://insight.bitpay.com/tx/62fdb1ad097744fdfc84173583ded9c25a52958d2858d12567206c360ab99327

**Comment by zachalam** [comment]
Hi Feiyan,
Sorry you've run into trouble. Can you please provide me with the name you tried to create? I'd be more than glad to help out.,

**Comment by feiyan-cs** [comment]
I think it was feiyanreader or feiyareader

**Comment by zachalam** [comment]
No worries! I've gone ahead and created the account you suggested. You can view it on the EOS mainnet here: https://eospark.com/MainNet/account/feiyanreader - Going to close this issue but feel free to open another if needed.

**Comment by ajjasatya** [comment]
Hi Zachalam, I am having the same issue. ive gone through the process three times now, paid each time and still my name hasn't shown up on the blockchain. 

my public key is:

EOS7ETUr81ZFxPm4sW8wSTaZ5eWPUTgwaCKrjeAFTFhb1T97WLVC9

and the name i was trying to get is: heavenwithin

would be great if you could help me out with this!

**Comment by zachalam** [comment]
So sorry you're running into trouble. Am working on a fix currently for this. I'll get this name registered alongside your public key ASAP and notify you.

**Comment by ajjasatya** [comment]
Hey there! I actually went through another provider and got my name
registered.. but a refund for the three times I paid would be cool! :)

**Comment by zachalam** [comment]
Absolutely, sorry about the troubles. Let me know what ethereum address you want the refund to go to.
